<?php

function olcgroups_menu() {
  return array(
    'test/groups' => array(
      'title' => 'OLC GROUPS TEST',
      'page callback' => '_olcgroups_test_groups_page',
      'access callback' => TRUE
    ),
    'test/groups/%group' => array(
      'title' => 'OLC GROUPS TEST',
      'page callback' => '_olcgroups_test_gid_page',
      'page arguments' => array(2),
      'access callback' => TRUE
    ),
  );
}

function _olcgroups_test_groups_page() {
  $content = '';

  dpm('Group');
  dpm(og_load(12));

  dpm('Is a member');
  dpm(og_is_member(12));

  dpm(og_user_access(12, 'edit_update_own_instruction_content'));


  return $content;
}

function _olcgroups_test_gid_page($group) {
  return 'Test gid page';
}

